# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lbutton', '0003_auto_20150314_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkbutton',
            name='chrome_file',
            field=models.FilePathField(null=True, path='/home/michael/WebSites/dev/git/codefisher_org/../www/media/lbutton/chrome'),
        ),
        migrations.AddField(
            model_name='linkbutton',
            name='firefox_file',
            field=models.FilePathField(null=True, path='/home/michael/WebSites/dev/git/codefisher_org/../www/media/lbutton/firefox'),
        ),
        migrations.AddField(
            model_name='linkbutton',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
